### ISSUE TITLE
Handling file input

### ISSUE THREAD

**Issue by muan** [github/file-attachment-element#2]
> Attach files via drag and drop or file input.

The element itself doesn't seem to care about file inputs. In dotcom we use a custom behavior that calls `fileattachment.attach(files)`. I think we can add some simple documentation for this, but I wonder what you all think about having the element listening on file input change instead?

It is not too much to add the custom hook, but considering an actual file input would be needed for accessibility, I think it'd be good if it comes by default.

cc @github/web-systems

**Comment by koddsson** [comment]
This sounds reasonable to me. 

> having the element listening on file input change instead?

Is this referring to replacing all the [listeners we currently have](https://github.com/github/file-attachment-element/blob/3127666318d71d8b898e5aca471958f0a154e24d/src/file-attachment-element.ts#L6-L10) with a single `change` one?

Added accessibility baked into the component would be a big 👍 from me.

**Comment by keithamus** [comment]
I think the drag and drop listeners are necessary to the functionality of this element.

Having it work via file input through listening to those events sounds good to me though!
